-- =====================================================================
-- Loan Portal — lender policies (from "Policy details as per 2024.xlsx")
-- Run AFTER schema.sql, in Supabase → SQL Editor. Safe to run again: it replaces the lender rows.
--
-- One row per lender policy column in the sheet (26 with data). Contact persons and phone
-- numbers from the sheet are NOT stored. Numbers such as minimum salary / CIBIL / age were read
-- from the sheet's text; the full original text of every row is kept in "policy" and is also
-- given to the Gemini assistant. Edit any value later in Table Editor → lenders.
-- The sheet describes PERSONAL LOAN policies. For other loan types results are marked "check with bank".
-- =====================================================================

create table if not exists public.lenders (
  id                    text primary key,
  bank_name             text not null,
  variant               text not null default '',      -- "Policy 2" when the sheet has several columns for one bank
  product               text not null default 'Personal Loan',
  min_salary_listed     integer,     -- ₹ per month, listed companies
  min_salary_unlisted   integer,     -- ₹ per month, non-listed companies
  min_cibil             integer,
  min_age               integer,
  max_age               integer,
  min_exp_months        integer,
  min_loan_amount       bigint,
  max_loan_amount       bigint,
  max_tenure_months     integer,
  max_foir_pct          numeric,     -- all EMIs as % of income
  roi_min               numeric,     -- % per year
  roi_max               numeric,
  unlisted_allowed      boolean,     -- null = not stated / depends on profile
  contract_emp_allowed  boolean,
  bpo_nbfc_allowed      boolean,     -- BPO, pharma, NBFC, insurance, real estate employers
  active                boolean not null default true,
  policy                jsonb not null default '{}'::jsonb,   -- "row. criterion" → original sheet text
  updated_at            timestamptz not null default now()
);
alter table public.lenders enable row level security;
drop policy if exists lenders_read on public.lenders;
create policy lenders_read on public.lenders for select to authenticated using (true);
revoke all on public.lenders from anon, authenticated;
grant select on public.lenders to authenticated;       -- read-only for signed-in users; edit in the Supabase dashboard

insert into public.lenders (id, bank_name, variant, product, min_salary_listed, min_salary_unlisted, min_cibil, min_age, max_age, min_exp_months, min_loan_amount, max_loan_amount, max_tenure_months, max_foir_pct, roi_min, roi_max, unlisted_allowed, contract_emp_allowed, bpo_nbfc_allowed, policy) values
  ('aditya_birla_finance_1', 'Aditya Birla Finance', 'Policy 1', 'Personal Loan', 25000, 40000, 700, 23, 59, 24, null, 5000000, null, 70, 10.5, null, true, null, true, '{"01. Listed Company": "25K+ (A,B,C)", "02. Non Listed Company": "40K+, pertnership and propritorship also can do", "03. CIBIL Enquiries": "5th enquirys with in 30 Days", "04. CIBIL - 0,1,2,3,4,5": "we can do", "05. CIBIL  (-1)": "we can do", "06. Minimum Cibil Score": "700", "07. last one Year - EMI Bounces in loans": "6m -1 bounce, 1 year 2 bounce, and last 3 months without bounce loan can do BT", "08. In CIBIL CC settled OR DPD''s": "case to case", "09. In CIBIL Loans settled OR DPD''s": "last 2 years track should not be settled, based on the new loan track can do it", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "last 2 years track should not be settled, based on the new loan track can do it", "11. Over dues In CIBIL cc": "we can take deviation", "12. Co applicant in HL Policy": "emi paying person should have income then will not considered, if there is any tencfer is there then 50% considered", "13. App Loans": "last 6 months 50K+ and more then 1 loan can not be possible", "15. Recently Taken PL": "3rd line should be adhithya birla", "16. Non Listed Company": "40K+ and MCA 3 years", "17. Contract employees": "current year should be more then 1.5Years + and it should be listed", "18. Man Power Companies": "can do it with the sme comp if 40K + other comp working also can be possible should be listed", "19. AGE": "23 Years to 59 Years", "20. Bachelor accommodation": "Pat Address verification bandatory", "21. PG accommodation": "Pat Address verification bandatory", "23. For BPO AND Pharma, NBFC, insurance, real estate": "he has official email ID confirmation bases can do", "24. Experience": "2 years, 25 years + not required", "25. Accomodation": "Any", "26. loan Amount": "a-50L, b-40L, c-40L+, d- 30L", "28. Part Payment": "after 6 months can do part payment 1 time in 1 years, upto 20% no charges", "29. Preclosure": "after 12 Emi 4%", "31. Eligibility": "foir - upto 70%, HL - files 5% extra", "33. Rate of interest": "10.5% non BT+", "34. Documents": "No payslip required, no address proof required,", "35. OD": "hybride OD, term loan hybride, flexy OD,", "36. Current address proof policy": "current address proof not required"}'::jsonb),
  ('aditya_birla_finance_2', 'Aditya Birla Finance', 'Policy 2', 'Personal Loan', null, null, 700, 23, null, 24, null, 4000000, null, null, 19.25, null, null, false, true, '{"01. Listed Company": "Depends on the salary and company category", "03. CIBIL Enquiries": "based on the housing loan track", "04. CIBIL - 0,1,2,3,4,5": "will be considered", "05. CIBIL  (-1)": "Applicable", "06. Minimum Cibil Score": "more than 700", "07. last one Year - EMI Bounces in loans": "as an exception accepted", "08. In CIBIL CC settled OR DPD''s": "Based on live track and vaild reason", "09. In CIBIL Loans settled OR DPD''s": "Based on live track and vaild reason", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "Based on live track and vaild reason", "11. Over dues In CIBIL cc": "applicable under proof", "15. Recently Taken PL": "Based on salary", "16. Non Listed Company": "Applicable, max 5L", "17. Contract employees": "No", "18. Man Power Companies": "Yes", "19. AGE": "23-55years", "20. Bachelor accommodation": "Yes, need permanent address verification or owners proof", "21. PG accommodation": "Yes, need permanent address verification or owners proof", "22. Credit History": "more than 700", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes, based on the company loan amount is decided", "24. Experience": "min 2year job stability", "25. Accomodation": "home, PG, bachelor", "26. loan Amount": "1L to 40L, based on the company category", "28. Part Payment": "After 1year", "31. Eligibility": "based on salary", "33. Rate of interest": "13.25-19.25% depends on the loan amount", "34. Documents": "KYC documents, 3months pay slip, 3months bank statement, passport size photo"}'::jsonb),
  ('axis_bank_1', 'Axis Bank', 'Policy 1', 'Personal Loan', 25000, null, 740, 21, 58, 12, null, 4000000, 84, 80, 9.99, null, false, false, null, '{"01. Listed Company": "25K+", "02. Non Listed Company": "not possible, MCA 5 years paid capital 2 Cr can add to listing", "03. CIBIL Enquiries": "less then 3 within 3 months, if profile is Good", "04. CIBIL - 0,1,2,3,4,5": "considered as -1", "05. CIBIL  (-1)": "Maximum 5 L, INTB - 10L, Cat d- not possible", "06. Minimum Cibil Score": "740+, less then that app score be good", "07. last one Year - EMI Bounces in loans": "last 6 months zero , 1 year 1 can be accepted", "08. In CIBIL CC settled OR DPD''s": "2 year PL clean track bases we can do process", "09. In CIBIL Loans settled OR DPD''s": "2 year PL clean track bases we can do process", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "2 year PL clean track bases we can do process", "11. Over dues In CIBIL cc": "before login should be clearbases can be done", "12. Co applicant in HL Policy": "emi paying person should have income then will not considered, if there is any trancfer is there then 50% considered", "13. App Loans": "4th loan should be Axis bank", "14. BT": "maximum 5 can be done BT, (app loan navi and incred can be done , minimum 6 months complete , od emi should be 6 months normal EMI", "15. Recently Taken PL": "1 Emi should be complete, proper end use need to give", "17. Contract employees": "Not possible", "19. AGE": "21 year to 58 Years", "20. Bachelor accommodation": "Can do it", "21. PG accommodation": "maximum 10 L", "23. For BPO AND Pharma, NBFC, insurance, real estate": "loan amount maximum 15l, foir 40%(blue coluers)", "24. Experience": "1 years over all", "26. loan Amount": "maximum 40L", "27. Tenure": "listed 84 months (ibil 740, sal 75K+, clean cibil) cont do BT", "28. Part Payment": "below 3 years- 3 %, after 3 years 2 %, abow 10L, after 12 m own fund closure zero, after 12m 1 time free,", "29. Preclosure": "below 3 years- 3 %, after 3 years 2 %, abow 10L, after 12 m own fund closure zero, after 12m 1 time free,", "30. Process": "digital- 3 days  , phtsical- 4 days,", "31. Eligibility": "Foir maximum - 80% super cat a , clean cibil, internal relation ship bases,tenure 5 years  (70%)", "33. Rate of interest": "9.99%+", "34. Documents": "current address proof mandatory (govt Doc) for physical login, digital login disbursement time should have proof", "37. NRI": "3 months salary credited mandatory in India"}'::jsonb),
  ('axis_bank_2', 'Axis Bank', 'Policy 2', 'Personal Loan', 25000, null, 700, 21, null, null, null, 4000000, null, null, null, null, null, false, true, '{"01. Listed Company": "25k min, for not listed companies 40k", "05. CIBIL  (-1)": "Applicable for upto Cat C, if it is internal salary account it fund upto 5L and if it is external salary account it fund upto 10L", "06. Minimum Cibil Score": "700 above", "07. last one Year - EMI Bounces in loans": "depends on the case", "08. In CIBIL CC settled OR DPD''s": "minor DPD''s are ok, they may have do the justifications.", "09. In CIBIL Loans settled OR DPD''s": "No", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "No", "11. Over dues In CIBIL cc": "if minor dues they may ask for the proofs, if it is high over dues then it will be trigered app code will be affected.", "15. Recently Taken PL": "Based on eligibility and income", "16. Non Listed Company": "No", "17. Contract employees": "No", "18. Man Power Companies": "depends on the company", "19. AGE": "21-55year", "20. Bachelor accommodation": "Yes", "21. PG accommodation": "No. But if the address proof is proper then it is given", "22. Credit History": "700 above", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes", "24. Experience": "more than one year", "25. Accomodation": "home, PG, bachelor", "26. loan Amount": "50k to 40L", "28. Part Payment": "Yes, it is done. After the 1st EMI every customer is eligible for part payment", "31. Eligibility": "based on category/salary slab", "33. Rate of interest": "varied based on the category", "34. Documents": "KYC documents, 3months pay slip, 6months banking, current address proof, photograph, 1 year experience letter"}'::jsonb),
  ('bajaj_finance_1', 'Bajaj Finance', 'Policy 1', 'Personal Loan', 36000, null, 700, 23, null, null, null, 5000000, null, null, 11.0, null, null, false, true, '{"01. Listed Company": "36k", "03. CIBIL Enquiries": "in the latest 30days, we look for 5 enquiries.", "05. CIBIL  (-1)": "No, they have stopped", "06. Minimum Cibil Score": "minimum 700", "07. last one Year - EMI Bounces in loans": "Applicable for 1 bounce", "08. In CIBIL CC settled OR DPD''s": "After loan is settled, the customer has to take 3L loan then they accept", "09. In CIBIL Loans settled OR DPD''s": "After loan is settled, the customer has to take 3L loan then they accept", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "Based on the color segment they consider", "11. Over dues In CIBIL cc": "clear it and get the loan", "15. Recently Taken PL": "Based on salary", "16. Non Listed Company": "Yes, color segment should be super green and customer should have housing loan", "17. Contract employees": "No", "18. Man Power Companies": "No", "19. AGE": "23-55years", "20. Bachelor accommodation": "Yes, own or rented is accepted", "21. PG accommodation": "No", "22. Credit History": "minimum 700", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes, if the company is listed", "25. Accomodation": "home, bachelor", "26. loan Amount": "1L to 50L", "28. Part Payment": "in over drop partly payment is accepted. In term loan it is not accepted.", "31. Eligibility": "based on salary", "33. Rate of interest": "above 10L personal loan 11%, based on the color segment", "34. Documents": "KYC documents, 3months pay slip, 6months bank statement, personal and official mail id, current address proof, passport size photo"}'::jsonb),
  ('bajaj_finance_2', 'Bajaj Finance', 'Policy 2', 'Personal Loan', 40000, null, 700, 23, null, 24, null, 5000000, null, null, 13.7, null, null, false, true, '{"01. Listed Company": "40k", "03. CIBIL Enquiries": "in the latest 30days, we look for below 4 enquiries.", "05. CIBIL  (-1)": "applicable for 30years of age", "06. Minimum Cibil Score": "minimum 700", "07. last one Year - EMI Bounces in loans": "as an exception accepted", "08. In CIBIL CC settled OR DPD''s": "No", "09. In CIBIL Loans settled OR DPD''s": "No", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "No", "11. Over dues In CIBIL cc": "No", "15. Recently Taken PL": "minimum 2months, and based on salary", "16. Non Listed Company": "Applicable, salary *10times", "17. Contract employees": "No", "18. Man Power Companies": "No", "19. AGE": "23-69years, for government employees upto 62years", "20. Bachelor accommodation": "No", "21. PG accommodation": "No", "22. Credit History": "minimum 700", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes, if the company is listed", "24. Experience": "min 2year job stability", "25. Accomodation": "home", "26. loan Amount": "1L to 50L", "28. Part Payment": "After 6 EMI unlimited charges", "31. Eligibility": "based on salary", "33. Rate of interest": "11.5-13.7% - based on salary, loan amount", "34. Documents": "KYC documents, 3months pay slip, 3months bank statement, photograph, address proof"}'::jsonb),
  ('bandhan_bank_1', 'Bandhan Bank', 'Policy 1', 'Personal Loan', 25000, null, 700, 21, 59, 12, null, 2500000, null, 70, 9.9, null, null, false, null, '{"01. Listed Company": "Cat -a,b,c 25K+, FOR D-40K+", "02. Non Listed Company": "Need to do the listing", "03. CIBIL Enquiries": "last 30 days 5th Bhandan, (max 6th)", "04. CIBIL - 0,1,2,3,4,5": "we can do", "05. CIBIL  (-1)": "we can do", "06. Minimum Cibil Score": "700+, 730 no deviation required", "07. last one Year - EMI Bounces in loans": "last 6 months- 2 bouncess, 3m - 1 Bounce can accept", "08. In CIBIL CC settled OR DPD''s": "latest 3 y should not be there, atleast 1 track 8 month minimum should be clean", "09. In CIBIL Loans settled OR DPD''s": "latest 3 y should not be there, atleast 1 track 8 month minimum should be clean", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "latest 3 y should not be there, atleast 1 track 8 month minimum should be clean", "11. Over dues In CIBIL cc": "With proper reason can do it, by clearing that, even after login also can do it", "12. Co applicant in HL Policy": "emi paying person should have income then will not considered, if there is any tencfer is there then 50% considered", "13. App Loans": "10K+ loans considered as PL, 4th loan should ba Bhandan", "15. Recently Taken PL": "Cat - A,B, min -3 Emis should be complete, c- 6 months complited,", "16. Non Listed Company": "not possible need to do the listing (1 day)", "17. Contract employees": "not possible", "18. Man Power Companies": "can do it with the sme comp if 40K + other comp working also can be possible", "19. AGE": "21 Years to 59 Years", "20. Bachelor accommodation": "Pat Address verification bandatory", "21. PG accommodation": "not possible  because address proof  needed", "23. For BPO AND Pharma, NBFC, insurance, real estate": "40K+", "24. Experience": "min 1 Year, for Govt  3months  also can do it", "25. Accomodation": "Family and BA", "26. loan Amount": "1 L to 25L maximum, Cat- C - 20L, D- 10L max", "28. Part Payment": "10L+ Partpayment is there same like HDFC bank, total tenure 2 times and with in 1 Year 1 time,", "29. Preclosure": "10L+- 0% , after 1 Year own funds, 6m+ - 4% closure charges are there", "31. Eligibility": "CC- 3times above only considered as 3%, below 0%, GL- will not considered, 6m below Emi''s not considered for foir, cibile 730 below- foir 5% will reduse, 25K to 30K-50%, till 60K- 60%, till 75k- 65%, above 75K+ 70%, multiplayer-A,B-upto24, (policy)", "33. Rate of interest": "roi-9.9%(15L+) to as HDFC ways", "34. Documents": "KYC documents, 3months pay slip, 4months bank statement, cAddress proof( rental agreement , bs, gas bill, WIFI Bill, post paid bill), govt ID any other address also fine,  above 6L PAT verificationmandatory, or Own house proof."}'::jsonb),
  ('bandhan_bank_2', 'Bandhan Bank', 'Policy 2', 'Personal Loan', 25000, null, 730, 21, null, null, null, 2500000, null, null, 11.9, null, null, false, null, '{"01. Listed Company": "cat A, B-25k, cat C-30k, cat D-40k", "03. CIBIL Enquiries": "in the latest 30days we look for 5 enquiries. Out of 5 at least 1 enquiry should be ours", "05. CIBIL  (-1)": "Applicable", "06. Minimum Cibil Score": "730+", "07. last one Year - EMI Bounces in loans": "Applicable for 1 bounce", "08. In CIBIL CC settled OR DPD''s": "3years should be completed. After that he is considered as -1 and the loan can be given", "09. In CIBIL Loans settled OR DPD''s": "3years should be completed. After that he is considered as -1 and the loan can be given", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "3years should be completed. After that he is considered as -1 and the loan can be given", "11. Over dues In CIBIL cc": "clear it and get the loan", "15. Recently Taken PL": "if 750+ score, 3EMI''s should be completed. CIBIL score <730 and 750> then 6EMI''s should be completed.", "16. Non Listed Company": "No", "17. Contract employees": "No, based on case to case", "18. Man Power Companies": "No", "19. AGE": "21-60years", "20. Bachelor accommodation": "Yes, need confirmation", "21. PG accommodation": "No", "22. Credit History": "730+", "23. For BPO AND Pharma, NBFC, insurance, real estate": "except real estate, based on salary min30k", "24. Experience": "job stability sholud be one year", "25. Accomodation": "home, bachelor", "26. loan Amount": "1L to 25L", "28. Part Payment": "with in a year, below 10L it is 2.5%, above 10L it is 0 charges", "31. Eligibility": "based on salary, multiplier method", "33. Rate of interest": "based on CIBIL score. Rate starts from 11.9%", "34. Documents": "KYC documents, 3months pay slip, 3months bank statement, if the customer has left the previous job then reliving letter, form 16 if the salary is above 50k"}'::jsonb),
  ('cholamandalam_finance_1', 'Cholamandalam Finance', 'Policy 1', 'Personal Loan', 25000, null, 685, 21, 60, 12, null, 3000000, 84, 70, 18.0, null, false, false, false, '{"01. Listed Company": "25K+", "02. Non Listed Company": "Not possible", "03. CIBIL Enquiries": "1 month 5 enquiries 6th chola", "04. CIBIL - 0,1,2,3,4,5": "not possible", "05. CIBIL  (-1)": "only govt emp", "06. Minimum Cibil Score": "685+ max 10L", "07. last one Year - EMI Bounces in loans": "1 year 1 bounce in 6 m should not be any bounce", "08. In CIBIL CC settled OR DPD''s": "live track bases can be done", "09. In CIBIL Loans settled OR DPD''s": "live track bases can be done", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "live track bases can be done", "11. Over dues In CIBIL cc": "live track bases can be done", "12. Co applicant in HL Policy": "emi paying person should have income then will not considered, if there is any tencfer is there then 50% considered", "13. App Loans": "tenure 1y+ - remaining lessthen 6 months  not considered", "14. BT": "6 months should be complete,  total 6, (PL, cc)", "15. Recently Taken PL": "we can do it depends on eligibility", "17. Contract employees": "Not possible", "18. Man Power Companies": "Not possible", "19. AGE": "21 years to 60 years", "20. Bachelor accommodation": "pat verification", "21. PG accommodation": "Not possible", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Not possible", "24. Experience": "1 year to 5 years", "26. loan Amount": "maximum 20 L, 1.5 L+ - 30L", "27. Tenure": "84 months (sal 40K+)", "28. Part Payment": "Not possible", "29. Preclosure": "4 %, after 6 months", "30. Process": "system login, 2 days", "31. Eligibility": "Foir - 55% to 70% , gold loan not going to obligate, cc - 3 times of salary of credit card obligation not going to be considered - if more then that is there then what ever is there only that will be obligated", "33. Rate of interest": "15 to 18%", "36. Current address proof policy": "current address proof required"}'::jsonb),
  ('cholamandalam_finance_2', 'Cholamandalam Finance', 'Policy 2', 'Personal Loan', 25000, null, 700, 21, null, null, null, 2000000, null, null, null, null, null, false, true, '{"01. Listed Company": "25k & above", "03. CIBIL Enquiries": "in the latest 30days we look for 6 enquiries.", "05. CIBIL  (-1)": "Applicable for the Government companies only", "06. Minimum Cibil Score": "700 above", "07. last one Year - EMI Bounces in loans": "Applicable for 1 bounce. Not applicable for latest 6months", "08. In CIBIL CC settled OR DPD''s": "Based on live track, depend upon credit card", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "Based on live track, depend upon credit card", "11. Over dues In CIBIL cc": "Based on live track, depend upon credit card", "15. Recently Taken PL": "Based on eligibility", "16. Non Listed Company": "No", "17. Contract employees": "No", "18. Man Power Companies": "No", "19. AGE": "21-55year", "20. Bachelor accommodation": "yes, should have permanent house", "21. PG accommodation": "No", "22. Credit History": "700 above", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Not applicable for NFC, real estate.", "24. Experience": "more than one year", "25. Accomodation": "home, bachelor", "26. loan Amount": "1L to 20L", "28. Part Payment": "Yes, yearly 2 times", "31. Eligibility": "based on the cam eligibility is considered", "33. Rate of interest": "0.15", "34. Documents": "KYC documents, 3months pay slip, 3months bank statement, gas bill, bank pass book"}'::jsonb),
  ('finnable_1', 'Finnable', '', 'Personal Loan', 20000, null, 680, 21, 54, 3, null, 1000000, null, 70, null, null, true, null, null, '{"01. Listed Company": "20k+ non metro city 15K+", "02. Non Listed Company": "propritorship  can do with 6 months salary credited required , comp GST number, comp should be 2 years", "03. CIBIL Enquiries": "750+ -13 enquiries, 700 + 5to 7 enquiries", "05. CIBIL  (-1)": "upto 4 Lakhs can do it", "06. Minimum Cibil Score": "680+", "07. last one Year - EMI Bounces in loans": "1 bounce with in 5 days payment", "08. In CIBIL CC settled OR DPD''s": "1 bounce with in 5 days payment, cibil shopud be morethen 700+ can be done, good profile 6 onths clen track", "09. In CIBIL Loans settled OR DPD''s": "1 bounce with in 5 days payment, cibil shopud be morethen 700+ can be done, good profile 6 onths clen track", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "1 bounce with in 5 days payment, cibil shopud be morethen 700+ can be done, good profile 6 onths clen track", "11. Over dues In CIBIL cc": "not possible to do", "12. Co applicant in HL Policy": "if co applicant 50% emi considered, if customer trancfer more then 50% then considered as ull emi", "13. App Loans": "recent more then 5 loans cont do it, 5th one should be finable", "15. Recently Taken PL": "1emi shild be complete", "17. Contract employees": "PF should be mandatory, or the costomer working in the same comp can be done.", "18. Man Power Companies": "PF should be mandatory, or the costomer working in the same comp can be done.", "19. AGE": "21 years, -1 cibil- 23 years, maximum age 54 Years", "24. Experience": "3 months should be there", "26. loan Amount": "7 Lakhs to 10 Lakhs", "28. Part Payment": "not available", "29. Preclosure": "after 6 months 6% charges, 13 months later 4%", "31. Eligibility": "Foir 70% for all", "33. Rate of interest": "starts 21.99+%", "34. Documents": "not required the address proof", "35. OD": "not Possible"}'::jsonb),
  ('fullerton_india_smfg_1', 'Fullerton India (SMFG)', '', 'Personal Loan', 25000, 25000, null, 21, null, 12, null, 2500000, 60, 70, 17.0, null, null, false, null, '{"01. Listed Company": "25k+", "02. Non Listed Company": "25k+", "03. CIBIL Enquiries": "90 days  10th enquiry fullerton", "04. CIBIL - 0,1,2,3,4,5": "can do", "05. CIBIL  (-1)": "can do", "06. Minimum Cibil Score": "score card syst should approve", "07. last one Year - EMI Bounces in loans": "6 months 1 bounce can do, with 3 onths no bounce", "08. In CIBIL CC settled OR DPD''s": "score card syst should approve", "09. In CIBIL Loans settled OR DPD''s": "score card syst should approve", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "score card syst should approve", "11. Over dues In CIBIL cc": "score card syst should approve", "12. Co applicant in HL Policy": "emi paying person should have income then will not considered, if there is any tencfer is there then 50% considered", "14. BT": "total pl- 7, cc- 5, car loan, t/w can do BT, app loan BT can do if they accept the dd for closing", "15. Recently Taken PL": "we can do it depends on eligibility", "17. Contract employees": "Not possible", "18. Man Power Companies": "Not possible", "19. AGE": "21 years", "20. Bachelor accommodation": "pat verification", "21. PG accommodation": "Not possible", "24. Experience": "1 year minimum", "26. loan Amount": "maximum 25 L", "27. Tenure": "60 months", "28. Part Payment": "Not possible", "29. Preclosure": "after 1 month can close with 7%, 18 months to 36 months- 5%, after 36 months free", "30. Process": "system approval and collect the doccuments, 5 days will take", "31. Eligibility": "foir - 70% maximum", "33. Rate of interest": "17% +", "36. Current address proof policy": "mandatory current address proof"}'::jsonb),
  ('hdfc_bank_1', 'HDFC Bank', 'Policy 1', 'Personal Loan', 25000, 50000, 700, null, null, null, null, null, null, null, null, null, null, null, null, '{"01. Listed Company": "25K+, Cat b-internal a/c- 30K, ext 35k, c- inter-35k, ext- 50K,", "02. Non Listed Company": "not possible, Cat d and e - 50K", "03. CIBIL Enquiries": "1m 3 enquiries+", "05. CIBIL  (-1)": "based on profile", "06. Minimum Cibil Score": "700+", "07. last one Year - EMI Bounces in loans": "2 maximum with genian reason", "08. In CIBIL CC settled OR DPD''s": "based on the clarification we can do it", "09. In CIBIL Loans settled OR DPD''s": "based on the clarification we can do it", "37. NRI": "Can do it"}'::jsonb),
  ('hdfc_bank_2', 'HDFC Bank', 'Policy 2', 'Personal Loan', 25000, null, 600, 21, null, 6, null, 7500000, null, null, null, null, null, false, true, '{"01. Listed Company": "based on category A -25k, cat B-30k, cat C-35k", "05. CIBIL  (-1)": "Applicable", "06. Minimum Cibil Score": "above 600", "07. last one Year - EMI Bounces in loans": "depends on case to case, based on the customer salary, with proof", "08. In CIBIL CC settled OR DPD''s": "No", "09. In CIBIL Loans settled OR DPD''s": "No", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "No", "11. Over dues In CIBIL cc": "applicable after clearing the credit card", "15. Recently Taken PL": "Based on eligibility and income", "16. Non Listed Company": "No", "17. Contract employees": "No", "18. Man Power Companies": "Yes", "19. AGE": "21-65years", "20. Bachelor accommodation": "yes, should have permanent house", "21. PG accommodation": "yes, should have permanent house", "22. Credit History": "above 600", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes", "24. Experience": "min 6months", "25. Accomodation": "home, PG, bachelor", "26. loan Amount": "50k to 75L", "28. Part Payment": "Depends on high value loans can done after one year", "31. Eligibility": "based on category/salary slab", "33. Rate of interest": "depends on salary slab", "34. Documents": "KYC documents, 3months pay slip, 6months banking, employee record"}'::jsonb),
  ('hdfc_bank_3', 'HDFC Bank', 'Policy 3', 'Personal Loan', 30000, null, 730, 21, null, 24, null, 7500000, null, null, 13.0, null, null, false, false, '{"01. Listed Company": "30k, with in HDFC 25k", "03. CIBIL Enquiries": "average 730+, based on face quality", "05. CIBIL  (-1)": "Applicable", "06. Minimum Cibil Score": "730+", "07. last one Year - EMI Bounces in loans": "on exception accepted, not accepted if delayed payment is done", "08. In CIBIL CC settled OR DPD''s": "accepted only credit card settlement is done, based on exception", "09. In CIBIL Loans settled OR DPD''s": "Not Applicable if settlement is done", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "Not Applicable if settlement is done", "11. Over dues In CIBIL cc": "applicable under proof", "15. Recently Taken PL": "Applicable", "16. Non Listed Company": "No", "17. Contract employees": "No", "18. Man Power Companies": "No", "19. AGE": "21-60years", "20. Bachelor accommodation": "yes, vericafication is done on visiting the native house", "21. PG accommodation": "yes", "22. Credit History": "730+", "23. For BPO AND Pharma, NBFC, insurance, real estate": "no, if listed yes provided. Not given to BPO", "24. Experience": "min 2year", "25. Accomodation": "home, PG, bachelor", "26. loan Amount": "50k to 75L", "28. Part Payment": "in 5years tenure 2times part time payment is done", "31. Eligibility": "based on salary", "33. Rate of interest": "apprx. 10.08 - 13%", "34. Documents": "KYC documents, 3months pay slip, 6months banking, form 16"}'::jsonb),
  ('icici_bank_1', 'ICICI Bank', '', 'Personal Loan', 30000, 75000, 730, null, null, 24, null, 10000000, null, 75, null, null, true, false, null, '{"01. Listed Company": "TOP COMP, ELITE, SUPER PRIME, - 30K, CIBLI 730+, PREFERED,- 35K, CIBIL-750, GOVT- 50K+", "02. Non Listed Company": "75K+, IF CIBIL IS GOOD (750) WE CAN DO FOR 50K", "03. CIBIL Enquiries": "UPTO 5 ENQUIRIES, IN 3 MONTHS  MORE WE CAN DO DEPENDS ON FILE", "05. CIBIL  (-1)": "PROFILE SHOULD BE GOOD, SAL SHOULD 50K+ 1ST TIME 15K", "06. Minimum Cibil Score": "730", "07. last one Year - EMI Bounces in loans": "BT LOAN SHOULD NOT BE BOUNCE,  MAX 2 BOUNCE WITH PROPER REASON,", "08. In CIBIL CC settled OR DPD''s": "WITH 1 YEAR SHOULD NOT BE THERE", "09. In CIBIL Loans settled OR DPD''s": "WITH 1 YEAR SHOULD NOT BE THERE, RECENT LOAN TRACK REQUIRED", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "WITH 1 YEAR SHOULD NOT BE THERE, RECENT LOAN TRACK REQUIRED", "11. Over dues In CIBIL cc": "WE CAN CLEAR WITH SUBJECTIVITY BASES", "12. Co applicant in HL Policy": "emi paying person should have income then will not considered, if there is any tencfer is there then 50% considered", "13. App Loans": "LOANS SHOULD BE LESS THEN 3 LOANS INCLUDING ICICI", "15. Recently Taken PL": "1 EMI SHOULD BE COMPLETE", "17. Contract employees": "NOT POSSIBLE", "18. Man Power Companies": "CAN DO IT WITH POLICY", "19. AGE": "2 YEARS EXP", "20. Bachelor accommodation": "OWN HOUSE PROOF REQUIRED", "21. PG accommodation": "OWN HOUSE PROOF REQUIRED", "23. For BPO AND Pharma, NBFC, insurance, real estate": "CASE TO CASE CAT", "24. Experience": "TOTAL 2 YEARS", "26. loan Amount": "UPTO 1 CR", "28. Part Payment": "AFTER 1 EMI 3 TIMES IN 1 YEARS,", "29. Preclosure": "12 M FREE, PART PAYMENT 18 M LATER WILL BE FREE", "31. Eligibility": "UP TO 75% IF HOME LOAN IS RUNNING MORE THEN 15L,", "36. Current address proof policy": "NOT MANDATORY, PAT SHOULD MATCH GOVT, BIOMATRIC AND BRANCH VISIT  WE CAN TAKE ANY ONE SHOULD MATCH,", "37. NRI": "CAN DO IT WITH POLICY"}'::jsonb),
  ('idfc_first_bank_1', 'IDFC First Bank', '', 'Personal Loan', 20000, null, 650, 23, null, 60, null, 10000000, null, null, 22.0, null, null, false, true, '{"01. Listed Company": "latest 3months net salary should be 20k", "03. CIBIL Enquiries": "max. 4 enquiries", "05. CIBIL  (-1)": "No", "06. Minimum Cibil Score": "650+", "07. last one Year - EMI Bounces in loans": "depends on the cibil score enquiry", "08. In CIBIL CC settled OR DPD''s": "depends on the cibil score enquiry, score card", "09. In CIBIL Loans settled OR DPD''s": "depends on the cibil score enquiry, score card", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "depends on the cibil score enquiry, score card", "11. Over dues In CIBIL cc": "if it is more than the 5times the salary they will not do", "15. Recently Taken PL": "Based on salary", "16. Non Listed Company": "No", "17. Contract employees": "No", "18. Man Power Companies": "only salaried companies which are listed", "19. AGE": "23-59years", "20. Bachelor accommodation": "Yes, loan amount will be restricted based on the verification", "21. PG accommodation": "Yes, loan amount will be restricted based on the verification", "22. Credit History": "650+", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes, based on the salary and the company is listed", "24. Experience": "min 5years of experience without any gap, current company there should be 6months of experience", "25. Accomodation": "home, PG, bachelor", "26. loan Amount": "1L to 1Cr, based on the customer profile", "28. Part Payment": "No. Preclosure that will be of 5% of principle amount", "31. Eligibility": "based on net salary", "33. Rate of interest": "10.99-22% based on the cases", "34. Documents": "KYC documents, 3months pay slip, 3months bank statement with details sheet, customers consent is needed, Driving License, voter ID, passport, gas bill, Wifi bill, postpaid bill"}'::jsonb),
  ('indusind_bank_1', 'IndusInd Bank', 'Policy 1', 'Personal Loan', 25000, null, 700, 21, null, 36, null, 5000000, null, null, 13.5, null, null, false, true, '{"01. Listed Company": "25k", "03. CIBIL Enquiries": "in the last 90days not more than 6 enquiries", "05. CIBIL  (-1)": "Applicable for listed companies, need employment proof of the customer", "06. Minimum Cibil Score": "more than 700", "07. last one Year - EMI Bounces in loans": "as an exception accepted", "08. In CIBIL CC settled OR DPD''s": "Based on live track and vaild reason", "09. In CIBIL Loans settled OR DPD''s": "Based on live track and vaild reason", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "No", "11. Over dues In CIBIL cc": "clear it and get the loan", "15. Recently Taken PL": "Based on salary", "16. Non Listed Company": "30k", "17. Contract employees": "No", "18. Man Power Companies": "No", "19. AGE": "21-60years", "20. Bachelor accommodation": "Yes, address proof is not mandatory. Proof is required when the loan is above 25L.", "21. PG accommodation": "depends on the case", "22. Credit History": "more than 700", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes, upto 5L the loan is given", "24. Experience": "min 3year job stability", "25. Accomodation": "home, PG, bachelor", "26. loan Amount": "50k to 50L", "28. Part Payment": "No. only foreclosure", "31. Eligibility": "based on salary", "33. Rate of interest": "10.35-13.5% depends on the loan amount", "34. Documents": "KYC documents, 3months pay slip, 3months bank statement, statement of account"}'::jsonb),
  ('indusind_bank_2', 'IndusInd Bank', 'Policy 2', 'Personal Loan', 25000, 30000, 700, 21, null, 24, null, 2500000, 84, 75, 10.25, null, null, false, false, '{"01. Listed Company": "Cat- a, b,-25k,", "02. Non Listed Company": "30K+, MCA 2 years", "03. CIBIL Enquiries": "2 months - 6th Indus inn,", "04. CIBIL - 0,1,2,3,4,5": "considered as -1", "05. CIBIL  (-1)": "sal minimum 30K, present comp 1 year wintage , 2 y exp proof, maximum 5L funding", "06. Minimum Cibil Score": "700+", "07. last one Year - EMI Bounces in loans": "last 3 months - 1 bounce can be accepted", "08. In CIBIL CC settled OR DPD''s": "1 year PL clean track bases we can do process", "09. In CIBIL Loans settled OR DPD''s": "1 year PL clean track bases we can do process", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "1 year PL clean track bases we can do process", "11. Over dues In CIBIL cc": "subjectivity clearence proof bases can be done", "12. Co applicant in HL Policy": "emi paying person should have income then will not considered, if there is any trancfer is there then 50% considered", "14. BT": "maximum 5 can be done BT, (app loan can be done based on dd closure, (PL, APP loan, Term loan, OD, ), minimum 3 months complete should be complited other loan 1 emi also can be done", "15. Recently Taken PL": "recent taken loan based on eligibility bases can be done, recent loan closures need to take source of funds", "17. Contract employees": "not possible, with out any proof we can proof as parmanent employ bases can be done", "19. AGE": "21 years", "20. Bachelor accommodation": "Pl track bases, PAT verification or Own house proof", "21. PG accommodation": "Pl track bases, PAT verification or Own house proof,", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Not possible, higher level can do it", "24. Experience": "minimum 2 years", "26. loan Amount": "25L+ - own house proof mandatory, 20L+ Present address proof required, below 20L address proof not required", "27. Tenure": "84 months", "28. Part Payment": "not available", "29. Preclosure": "12 months + - free charges", "30. Process": "minimum 3 days to 5 days", "31. Eligibility": "Foir maximum 75%( house peoof bases)", "33. Rate of interest": "10.25%+", "37. NRI": "1 sal credit bases can do it,"}'::jsonb),
  ('kotak_mahindra_bank_1', 'Kotak Mahindra Bank', '', 'Personal Loan', 20000, null, 700, 18, 60, null, 3000000, 150000000, null, null, 10, 13, null, true, true, '{"01. Listed Company": "20k", "03. CIBIL Enquiries": "secured enquiry 5 but not more than 8", "04. CIBIL - 0,1,2,3,4,5": "Applicable", "05. CIBIL  (-1)": "Applicable", "06. Minimum Cibil Score": "above 700", "07. last one Year - EMI Bounces in loans": "not accepted if this has happened In the last 3months, accepted if this has happened before 3months for 1 bounce", "08. In CIBIL CC settled OR DPD''s": "not applicable if settled, based on DPD and with proof it is accepted", "09. In CIBIL Loans settled OR DPD''s": "accepted based on exceptional reason and with proof", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "accepted for consumer, T/W is not accepted", "11. Over dues In CIBIL cc": "accepted", "15. Recently Taken PL": "accepted, based on the loans taken", "16. Non Listed Company": "accepted for above 20k salary", "17. Contract employees": "accepted for above 20k salary", "18. Man Power Companies": "accepted for above 20k salary", "19. AGE": "18-60years", "20. Bachelor accommodation": "Not applicable for single applicant", "21. PG accommodation": "applicable", "22. Credit History": "above 700", "23. For BPO AND Pharma, NBFC, insurance, real estate": "except real estate, applicable for all others", "24. Experience": "more than one year", "25. Accomodation": "home, PG, bachelor", "26. loan Amount": "30L to 15Cr", "28. Part Payment": "applicable, below 6months 20%part payment ends, after 12 months can be done anytime", "33. Rate of interest": "10-13%pa", "34. Documents": "KYC documents, income documents, property documents"}'::jsonb),
  ('muthoot_finance_1', 'Muthoot Finance', '', 'Personal Loan', 20000, null, 675, 23, null, 24, null, 1000000, null, null, 25.0, null, null, false, true, '{"01. Listed Company": "cat A, B -20k, cat C, D - 25k", "03. CIBIL Enquiries": "in the latest 30days, we look for 6 enquiries. 7th should be thiers", "04. CIBIL - 0,1,2,3,4,5": "Based on salary", "05. CIBIL  (-1)": "Applicable, 1.5L", "06. Minimum Cibil Score": "minimum 675", "07. last one Year - EMI Bounces in loans": "not accecpted if this has happened in the last 3months, based the profile it will be accepted", "08. In CIBIL CC settled OR DPD''s": "Based on live track", "09. In CIBIL Loans settled OR DPD''s": "No", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "Based on live track", "11. Over dues In CIBIL cc": "applicable under proof", "15. Recently Taken PL": "Based on salary", "16. Non Listed Company": "upto 5L", "17. Contract employees": "No", "18. Man Power Companies": "If the company is listed then accepted", "19. AGE": "23-55years, for government employees upto 68years", "20. Bachelor accommodation": "Applicable based on 5L loan track", "21. PG accommodation": "No", "22. Credit History": "minimum 675", "23. For BPO AND Pharma, NBFC, insurance, real estate": "yes, based on the company", "24. Experience": "min 2year job stability", "25. Accomodation": "home, bachelor", "26. loan Amount": "1L to 10L", "28. Part Payment": "No. only foreclosure", "31. Eligibility": "based on salary", "33. Rate of interest": "14.5-25% as per the CIBIL, profile and company catergory", "34. Documents": "KYC documents, 3months pay slip, 3months bank statement, passport, gas bill 2months, rental agrement mininum 90days old, Driving license"}'::jsonb),
  ('piramal_finance_1', 'Piramal Finance', 'Policy 1', 'Personal Loan', 27500, 27000, 700, 21, 60, 12, null, 2500000, 72, 75, 11.99, 27.49, null, false, null, '{"01. Listed Company": "27.5k+", "02. Non Listed Company": "27k+", "03. CIBIL Enquiries": "last 14 days 7th one piramal", "04. CIBIL - 0,1,2,3,4,5": "maximum 6L. ROI 20%+", "05. CIBIL  (-1)": "maximum 6L. ROI 20%+", "06. Minimum Cibil Score": "700+", "07. last one Year - EMI Bounces in loans": "2 bouncess", "08. In CIBIL CC settled OR DPD''s": "with valid reason can do it", "09. In CIBIL Loans settled OR DPD''s": "1 year live track", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "1 year live track", "11. Over dues In CIBIL cc": "clearing proof required", "12. Co applicant in HL Policy": "emi paying person should have income then will not considered, if there is any tencfer is there then 100% considered", "13. App Loans": "more then 7 should not be there", "14. BT": "app loans, cc, PL,  can do it but total 3 can do the BT", "15. Recently Taken PL": "we can do it depends on eligibility", "17. Contract employees": "Not possible", "18. Man Power Companies": "maximum 5 L", "19. AGE": "21 years to 60 years", "20. Bachelor accommodation": "pat own house proof required", "21. PG accommodation": "pat own house proof required", "24. Experience": "6 months minimum, total 1 year exp", "26. loan Amount": "open market 15L. Listed 25L", "27. Tenure": "72 months", "28. Part Payment": "after 1 months free charges", "29. Preclosure": "after 1 months free charges", "30. Process": "Digital process 1 to 2 days", "31. Eligibility": "Foire- max 75%, gold loan will not obligate,", "33. Rate of interest": "Roi 11.99% to 27.49%", "36. Current address proof policy": "mandatory current address proof", "37. NRI": "can do it with letter that to continue in bangalore, same comp 3 months required"}'::jsonb),
  ('piramal_finance_2', 'Piramal Finance', 'Policy 2', 'Personal Loan', 28000, null, 700, 21, null, 24, null, 1200000, null, null, 25.99, null, null, false, true, '{"01. Listed Company": "28k, PF is compulsory. If not form 26 is needed", "03. CIBIL Enquiries": "in the latest 30days, we look for below 7 enquiries.", "04. CIBIL - 0,1,2,3,4,5": "will be considered", "05. CIBIL  (-1)": "5L max and ROI is 25.99%- any salary", "06. Minimum Cibil Score": "minimum 700", "07. last one Year - EMI Bounces in loans": "not accecpted if this has happened in the last 3months, accepted if it happened in the last 6months", "08. In CIBIL CC settled OR DPD''s": "Based on live track and vaild reason", "09. In CIBIL Loans settled OR DPD''s": "Based on live track and vaild reason", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "Based on live track and vaild reason", "11. Over dues In CIBIL cc": "applicable for below 2k with better track", "15. Recently Taken PL": "Based on salary", "16. Non Listed Company": "3year MCA should be there", "17. Contract employees": "No", "18. Man Power Companies": "5L with offer letter is needed", "19. AGE": "21-60years, for government employees upto 63years", "20. Bachelor accommodation": "Yes, need owners proof, 6months bank statement is needed", "21. PG accommodation": "3months rental agreement, passport, gas bill, gas book, 3months bank statement is needed", "22. Credit History": "minimum 700", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes, upto 5L the loan is given", "24. Experience": "present company 6 months, overall 2years", "25. Accomodation": "home, PG, bachelor", "26. loan Amount": "1L to 12L", "28. Part Payment": "After 1 EMI unlimited charges", "31. Eligibility": "based on salary", "33. Rate of interest": "12.9-25.99%, rates depends on app score", "34. Documents": "KYC documents, 3months pay slip, 3months bank statement, live selfie photo"}'::jsonb),
  ('piramal_finance_3', 'Piramal Finance', 'Policy 3', 'Personal Loan', 27500, null, 650, 21, null, null, null, 2500000, null, null, 24.99, null, null, false, true, '{"01. Listed Company": "27.5k", "03. CIBIL Enquiries": "in the latest 30days, we look for 5 enquiries.", "04. CIBIL - 0,1,2,3,4,5": "will be considered", "05. CIBIL  (-1)": "Applicable", "06. Minimum Cibil Score": "650+", "07. last one Year - EMI Bounces in loans": "Applicable in the last 3months, based the profile it will be accepted", "08. In CIBIL CC settled OR DPD''s": "Based on live track", "09. In CIBIL Loans settled OR DPD''s": "Based on live track", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "Based on profile", "11. Over dues In CIBIL cc": "clear it and get the loan", "15. Recently Taken PL": "Based on salary", "16. Non Listed Company": "Yes, based on profile", "17. Contract employees": "No", "18. Man Power Companies": "Max. 5L fund will be done", "19. AGE": "21-60years", "20. Bachelor accommodation": "Yes, need owners proof", "21. PG accommodation": "No", "22. Credit History": "650+", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes", "24. Experience": "minimum one year", "25. Accomodation": "home, bachelor", "26. loan Amount": "cat A & cat B 1L to 25L,  12L to 15L based on the profile not listed", "28. Part Payment": "After 1 EMI unlimited charges", "31. Eligibility": "based on salary", "33. Rate of interest": "12.99 -24.99%", "34. Documents": "KYC documents, 3months pay slip, 6months bank statement, gas bill, gas book with in 60months, postpaid bill with in 30days, rental agrement mininum 90days old"}'::jsonb),
  ('poonawalla_fincorp_1', 'Poonawalla Fincorp', 'Policy 1', 'Personal Loan', 30000, 75000, 700, 21, 60, 24, null, 5000000, 84, 75, 11.5, 11.99, null, false, null, '{"01. Listed Company": "a to b- 30K,", "02. Non Listed Company": "mca should be 5 years - 75K - 5Lakhs", "03. CIBIL Enquiries": "3 months 8 nenquiries, 9th one should be Poonawala,", "05. CIBIL  (-1)": "only super cat a  and cat a non metro location can be doone", "06. Minimum Cibil Score": "700+", "07. last one Year - EMI Bounces in loans": "6 months bt case - 1 bounce,", "08. In CIBIL CC settled OR DPD''s": "6 months bt case - 1 bounce, 1 year track clean", "09. In CIBIL Loans settled OR DPD''s": "1 year track should be there", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "1 year track should be there", "11. Over dues In CIBIL cc": "WE CAN CLEAR WITH SUBJECTIVITY BASES", "12. Co applicant in HL Policy": "co applicant means 50% will be considered as 50%,", "14. BT": "app loans BT can do , 50K+ can be done BT, total 8 BT can be done, (cc-6, Loans- 3, app loans- 3, term loans - 5)", "15. Recently Taken PL": "we can do it depends on eligibility", "17. Contract employees": "Not possible", "18. Man Power Companies": "same comp working with loan track should be there", "19. AGE": "21 years to 60 Years,", "20. Bachelor accommodation": "1year PL track", "21. PG accommodation": "1year PL track", "24. Experience": "minimum 2 years", "26. loan Amount": "maximum 50 Lakhs", "27. Tenure": "84 months", "28. Part Payment": "multiple times can do", "29. Preclosure": "after 6 months can do", "30. Process": "system process - fresh 1 day (1to 15L), 2 to 3 days", "31. Eligibility": "foire - a- 75%, sal should be 75K,", "33. Rate of interest": "Roi fresh funding 11.5%, 11.99%", "34. Documents": "current address proof required", "35. OD": "can be done BT", "36. Current address proof policy": "current address proof required"}'::jsonb),
  ('poonawalla_fincorp_2', 'Poonawalla Fincorp', 'Policy 2', 'Personal Loan', 30000, null, 700, 21, null, null, null, 5000000, null, null, 18.0, null, null, false, true, '{"01. Listed Company": "30k", "03. CIBIL Enquiries": "more than 700", "04. CIBIL - 0,1,2,3,4,5": "will be considered", "05. CIBIL  (-1)": "Applicable", "06. Minimum Cibil Score": "more than 700", "07. last one Year - EMI Bounces in loans": "as an exception accepted", "08. In CIBIL CC settled OR DPD''s": "No", "09. In CIBIL Loans settled OR DPD''s": "No, based on live track", "10. In CIBIL T/W or Consumer Loans settled OR DPD''s": "Based on live track", "11. Over dues In CIBIL cc": "No", "15. Recently Taken PL": "No", "16. Non Listed Company": "No", "17. Contract employees": "No", "18. Man Power Companies": "No", "19. AGE": "21 - 60years", "20. Bachelor accommodation": "own house is mandatatory", "21. PG accommodation": "Rental agreement, gas bill, telecom bill", "22. Credit History": "more than 700", "23. For BPO AND Pharma, NBFC, insurance, real estate": "Yes, if the company is listed", "24. Experience": "more than one year", "25. Accomodation": "home, PG, bachelor", "26. loan Amount": "1L to 50L", "28. Part Payment": "After 6months unlimited", "33. Rate of interest": "15-18%", "34. Documents": "KYC documents, 3months pay slip, 6months banking, CC documents, home loan documents"}'::jsonb)
on conflict (id) do update set bank_name = excluded.bank_name, variant = excluded.variant, product = excluded.product, min_salary_listed = excluded.min_salary_listed, min_salary_unlisted = excluded.min_salary_unlisted, min_cibil = excluded.min_cibil, min_age = excluded.min_age, max_age = excluded.max_age, min_exp_months = excluded.min_exp_months, min_loan_amount = excluded.min_loan_amount, max_loan_amount = excluded.max_loan_amount, max_tenure_months = excluded.max_tenure_months, max_foir_pct = excluded.max_foir_pct, roi_min = excluded.roi_min, roi_max = excluded.roi_max, unlisted_allowed = excluded.unlisted_allowed, contract_emp_allowed = excluded.contract_emp_allowed, bpo_nbfc_allowed = excluded.bpo_nbfc_allowed, policy = excluded.policy, updated_at = now();

-- ---------------------------------------------------------------------
-- check_lenders(application id): compare one application with every lender.
-- Runs as the signed-in person (RLS applies), so it only works on their own applications.
--   result  'eligible'      can apply: meets every written rule
--           'check'         may apply: nothing breaks a rule, but something needs confirming
--           'not_eligible'  can't apply: breaks at least one written rule
-- Never a guarantee — the lender makes the final decision.
-- ---------------------------------------------------------------------
create or replace function public.check_lenders(p_application uuid)
returns table (
  lender_id text, bank_name text, variant text, result text, score integer,
  reasons_ok text[], reasons_check text[], reasons_fail text[],
  roi_min numeric, roi_max numeric, max_loan bigint, eligible_amount bigint, est_emi integer, max_foir numeric
)
language plpgsql stable security invoker set search_path = public as $$
declare
  a record;
  d jsonb; v_income numeric; v_emi numeric; v_cibil integer; v_age integer; v_exp integer; v_amount numeric; v_months integer;
  v_comp text; v_pay text; v_ind text; v_loan text; v_enq integer; v_bounce integer; v_settled text;
begin
  select * into a from public.applications where id = p_application;     -- RLS: only your own
  if not found then raise exception 'Application not found.' using errcode = 'P0002'; end if;
  d := a.data;
  v_income := nullif(regexp_replace(coalesce(d->'work'->>'income',''), '[^0-9.]', '', 'g'), '')::numeric
            + coalesce(nullif(regexp_replace(coalesce(d->'work'->>'otherIncome',''), '[^0-9.]', '', 'g'), '')::numeric, 0);
  v_emi    := coalesce(nullif(regexp_replace(coalesce(d->'loan'->>'existingEmi',''), '[^0-9.]', '', 'g'), '')::numeric, 0);
  v_cibil  := nullif(regexp_replace(coalesce(d->'loan'->>'cibil',''), '[^0-9]', '', 'g'), '')::integer;
  v_age    := case when coalesce(d->'personal'->>'dob','') ~ '^\d{4}-\d{2}-\d{2}$' then extract(year from age((d->'personal'->>'dob')::date))::integer end;
  v_exp    := round(coalesce(nullif(regexp_replace(coalesce(d->'work'->>'experience',''), '[^0-9.]', '', 'g'), '')::numeric, 0) * 12)::integer;
  v_amount := nullif(regexp_replace(coalesce(d->'loan'->>'amount',''), '[^0-9.]', '', 'g'), '')::numeric;
  v_months := round(coalesce(nullif(regexp_replace(coalesce(d->'loan'->>'tenure',''), '[^0-9.]', '', 'g'), '')::numeric, 5) * 12)::integer;
  v_comp   := lower(coalesce(d->'work'->>'companyType', ''));        -- listed | unlisted | government | proprietorship | partnership
  v_pay    := lower(coalesce(d->'work'->>'payroll', ''));            -- permanent | contract | third_party | self_employed
  v_ind    := lower(coalesce(d->'work'->>'industry', ''));
  v_loan   := coalesce(d->'loan'->>'loanType', '');
  v_enq    := nullif(regexp_replace(coalesce(d->'loan'->>'enquiries',''), '[^0-9]', '', 'g'), '')::integer;
  v_bounce := nullif(regexp_replace(coalesce(d->'loan'->>'bounces',''), '[^0-9]', '', 'g'), '')::integer;
  v_settled:= lower(coalesce(d->'loan'->>'settled', ''));

  return query
  with base as (
    select l.*,
      least(coalesce(l.max_tenure_months, v_months), v_months) as months,
      coalesce(l.roi_min, 12)::numeric as rate,
      case when v_comp in ('unlisted','proprietorship','partnership') then coalesce(l.min_salary_unlisted, l.min_salary_listed) else l.min_salary_listed end as min_sal
    from public.lenders l where l.active
  ), calc as (
    select b.*,
      case when b.rate > 0 and b.months > 0 then (b.rate / 1200) * power(1 + b.rate / 1200, b.months) / (power(1 + b.rate / 1200, b.months) - 1) end as emi_factor
    from base b
  ), rules as (
    select c.*,
      case when c.emi_factor is not null and v_income is not null
           then greatest(0, (v_income * coalesce(c.max_foir_pct, 60) / 100 - v_emi) / c.emi_factor) end as foir_cap,
      array_remove(array[
        case when v_cibil is not null and c.min_cibil is not null and v_cibil < c.min_cibil then format('CIBIL %s is below the minimum of %s', v_cibil, c.min_cibil) end,
        case when v_income is not null and c.min_sal is not null and v_income < c.min_sal then format('Income ₹%s is below the minimum of ₹%s a month', to_char(v_income, 'FM99,99,99,999'), to_char(c.min_sal, 'FM99,99,99,999')) end,
        case when v_age is not null and c.min_age is not null and v_age < c.min_age then format('Age %s is below the minimum of %s', v_age, c.min_age) end,
        case when v_age is not null and c.max_age is not null and v_age > c.max_age then format('Age %s is above the maximum of %s', v_age, c.max_age) end,
        case when c.min_exp_months is not null and v_exp < c.min_exp_months then format('Work experience of %s months is below the minimum of %s months', v_exp, c.min_exp_months) end,
        case when v_amount is not null and c.min_loan_amount is not null and v_amount < c.min_loan_amount then format('Lends from ₹%s upwards', to_char(c.min_loan_amount, 'FM99,99,99,999')) end,
        case when v_comp in ('unlisted','proprietorship','partnership') and c.unlisted_allowed is false then 'Does not lend to employees of non-listed companies' end,
        case when v_pay in ('contract','third_party') and c.contract_emp_allowed is false then 'Does not lend to contract / third-party payroll employees' end,
        case when c.bpo_nbfc_allowed is false and v_ind in ('bpo','pharma','nbfc','insurance','real_estate') then 'Does not lend to employees in this industry' end,
        case when v_settled = 'open' then 'A settled loan is still showing on the credit report' end
      ]::text[], null) as fail
    from calc c
  ), scored as (
    select r.*,
      array_remove(array[
        case when v_cibil is not null and r.min_cibil is not null and v_cibil >= r.min_cibil then format('CIBIL %s meets the minimum of %s', v_cibil, r.min_cibil) end,
        case when v_income is not null and r.min_sal is not null and v_income >= r.min_sal then format('Income meets the minimum of ₹%s a month', to_char(r.min_sal, 'FM99,99,99,999')) end,
        case when v_age is not null and (r.min_age is not null or r.max_age is not null) and v_age between coalesce(r.min_age, 0) and coalesce(r.max_age, 200) then format('Age %s is within their limit', v_age) end,
        case when r.min_exp_months is not null and v_exp >= r.min_exp_months then 'Work experience is enough' end,
        case when r.foir_cap is not null and v_amount is not null and r.foir_cap >= v_amount then 'Income supports the EMI for the full amount' end
      ]::text[], null) as ok,
      array_remove(array[
        case when v_loan <> '' and v_loan <> r.product then format('Sheet has %s rules only; confirm their %s policy', lower(r.product), v_loan) end,
        case when v_cibil is null then 'CIBIL score not given' end,
        case when v_comp = '' then 'Employer type (listed / non-listed) not given' end,
        case when v_comp in ('unlisted','proprietorship','partnership') and r.unlisted_allowed is null then 'Non-listed companies: depends on the company category' end,
        case when v_pay = '' then 'Payroll type not given' end,
        case when v_pay in ('contract','third_party') and r.contract_emp_allowed is null then 'Contract employees: not stated in the sheet' end,
        case when r.min_cibil is null then 'Minimum CIBIL not stated in the sheet' end,
        case when v_amount is not null and r.max_loan_amount is not null and v_amount > r.max_loan_amount then format('Maximum loan is ₹%s', to_char(r.max_loan_amount, 'FM99,99,99,999')) end,
        case when r.foir_cap is not null and v_amount is not null and r.foir_cap < v_amount then format('Income supports about ₹%s at %s%% interest', to_char(round(r.foir_cap, -3), 'FM99,99,99,999'), r.rate) end,
        case when v_enq is not null and v_enq > 4 then format('%s credit enquiries in 3 months is high', v_enq) end,
        case when v_bounce is not null and v_bounce > 0 then format('%s EMI bounce(s) in 12 months', v_bounce) end,
        case when v_settled = 'cleared' then 'A settled loan in the past: lender will ask for the closure letter' end,
        case when v_months > coalesce(r.max_tenure_months, v_months) then format('Tenure limited to %s months', r.max_tenure_months) end
      ]::text[], null) as chk
    from rules r
  )
  select s.id, s.bank_name, s.variant,
    case when cardinality(s.fail) > 0 then 'not_eligible'
         when cardinality(s.chk) > 0 then 'check' else 'eligible' end,
    (case when cardinality(s.fail) > 0 then greatest(5, 40 - 10 * cardinality(s.fail))
          else greatest(50, 100 - 7 * cardinality(s.chk)) end)::integer,
    s.ok, s.chk, s.fail, s.roi_min, s.roi_max, s.max_loan_amount,
    case when v_amount is null then null else round(least(v_amount, coalesce(s.max_loan_amount, v_amount), coalesce(s.foir_cap, v_amount)), -3)::bigint end,
    case when s.emi_factor is null or v_amount is null then null
         else round(least(v_amount, coalesce(s.max_loan_amount, v_amount), coalesce(s.foir_cap, v_amount)) * s.emi_factor)::integer end,
    s.max_foir_pct
  from scored s
  order by case when cardinality(s.fail) > 0 then 3 when cardinality(s.chk) > 0 then 2 else 1 end,
           (case when cardinality(s.fail) > 0 then 0 else 100 - 7 * cardinality(s.chk) end) desc, s.roi_min nulls last, s.bank_name, s.variant;
end $$;
revoke execute on function public.check_lenders(uuid) from public, anon;
grant execute on function public.check_lenders(uuid) to authenticated;

-- Saved Gemini analysis for an application (written by the website after the assistant answers).
alter table public.applications add column if not exists ai_analysis jsonb;
